name: setup-with-deploy
run-name: deploy by ${{ github.actor }} 
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: Install and Build
        shell: bash
        run: |
          bun install
          bun run build
        working-directory: .
      - name: Check wrangler.toml
        run: cat wrangler.toml
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          wranglerVersion: "3.51.2"
          command: pages deploy 
